# Generated by Django 4.2.7 on 2023-11-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstnamear', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('lastnamear', models.CharField(max_length=50)),
                ('firstnameen', models.CharField(max_length=50)),
                ('lastnameen', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('singater', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=128)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
