# Generated by Django 4.2.7 on 2023-11-16 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='supvaser_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supvaser', to='Client.clientuser'),
        ),
    ]
